"""empty message

Revision ID: 5e5f3c687674
Revises: d8b28d7a629b
Create Date: 2025-06-05 00:19:42.402219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5f3c687674'
down_revision: Union[str, None] = 'd8b28d7a629b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfiles', sa.Column('yandex_access_token', sa.String(), nullable=True))
    op.add_column('UserProfiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('UserProfiles', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfiles', 'name')
    op.drop_column('UserProfiles', 'email')
    op.drop_column('UserProfiles', 'yandex_access_token')
    # ### end Alembic commands ###
