"""empty message

Revision ID: bf4b35c76d5d
Revises: 5e5f3c687674
Create Date: 2025-06-05 00:28:18.927675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4b35c76d5d'
down_revision: Union[str, None] = '5e5f3c687674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfiles', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('UserProfiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('UserProfiles', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
